In [33]:
%pip install tensorflow

from tensorflow import keras

import numpy as np

Note: you may need to restart the kernel to use updated packages.


# 12회차 과제
목표: NAND gate를 Python 함수와 Keras를 이용해 각각 구현해 보기.  
(수업 자료의 `과제 연계 실습` 참고)

## NAND Gate

NAND Gate란, AND gate의 역으로써 x_1, x_2가 모두 1일 때만 0을 반환하고, 나머지는 1을 반환하는 논리 회로이다.  
아래 빈칸을 채워 NAND gate를 구현하시오.

In [29]:
def NAND_gate(x1, x2):
    w1 = -0.3
    w2 = -0.3
    b = 0.2

    if x1 * w1 + x2 * w2 >= -b:
        return 1
    else:
        return 0

for x1 in (0, 1):
    for x2 in (0, 1):
        print(f"NAND({x1}, {x2}): {NAND_gate(x1, x2)}")

NAND(0, 0): 1
NAND(0, 1): 0
NAND(1, 0): 0
NAND(1, 1): 0


이번에는 Keras를 활용해 구현하시오.

In [34]:
NAND_gate_model = keras.models.Sequential([
    keras.layers.InputLayer(
        shape=(2,),
    ),
    keras.layers.Dense(
        units=1,
        activation=keras.activations.sigmoid
    )
])

NAND_gate_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3 (12.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

In [52]:
import numpy as np

prob = NAND_gate_model(np.array([[0, 0], [0, 1], [1, 0], [1, 1]])).numpy()


display(prob)

def prob_to_pred(prob):
    if prob >= 0.5:
        return 1
    else:
        return 0


display(np.apply_along_axis(prob_to_pred, 1, prob))

NAND_gate_model.compile(optimizer='adamw', loss=keras.losses.BinaryCrossentropy, metrics=['accuracy'])

NAND_gate_model.fit(np.array([[0, 0], [0, 1], [1, 0], [1, 1]]), np.array([[1], [0], [0], [0]]), epochs=700)

array([[0.41711903],
       [0.17352512],
       [0.25274327],
       [0.09027593]], dtype=float32)

array([0, 0, 0, 0])

Epoch 1/700
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 0.7500 - loss: 0.3627
Epoch 2/700
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.3626
Epoch 3/700
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.3624
Epoch 4/700
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.3622
Epoch 5/700
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.3621
Epoch 6/700
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7500 - loss: 0.3619
Epoch 7/700
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7500 - loss: 0.3617
Epoch 8/700
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.3616
Epoch 9/700
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7500 - loss: 0.3614
Epoch 10/700
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.3612
Epoch 11/700
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.3611
Epoch 12/700
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - lo

In [54]:
prob_after_training = NAND_gate_model(np.array([[0, 0], [0, 1], [1, 0], [1, 1]])).numpy()

display(prob_after_training)
display(np.apply_along_axis(prob_to_pred, 1, prob_after_training))
display(NAND_gate_model.weights)

array([[0.54899096],
       [0.15668459],
       [0.22888045],
       [0.04334115]], dtype=float32)

array([1, 0, 0, 0])

[<Variable path=sequential/dense/kernel, shape=(2, 1), dtype=float32, value=[[-1.4112383]
  [-1.8797007]]>,
 <Variable path=sequential/dense/bias, shape=(1,), dtype=float32, value=[0.19659473]>]